package com.example.entrega1.services;

// ELABORAR FUNCIONES A SOLICTADAS POR ACÁ -> CORE DE LA LOGICA DE NEGOCIOS
// -> PROCURAR DE QUE ESTÉ BIEN REALIZADO
// -> ESTE SERVICIO SOLO USA GETS PARA CALCULAR LAS COSAS
public class SistemaService {
}
